<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Persona;

class PersonaSeeder extends Seeder
{
    public function run(): void
    {
        $characters = [
            ['nombres' => 'Tony', 'apellidos' => 'Stark', 'genero' => 'masculino', 'centro' => 'Avengers Tower', 'regional' => 'Nueva York'],
            ['nombres' => 'Daenerys', 'apellidos' => 'Targaryen', 'genero' => 'femenino', 'centro' => 'Dragonstone', 'regional' => 'Westeros'],
            ['nombres' => 'Hermione', 'apellidos' => 'Granger', 'genero' => 'femenino', 'centro' => 'Hogwarts School', 'regional' => 'Reino Unido'],
            ['nombres' => 'Peter', 'apellidos' => 'Parker', 'genero' => 'masculino', 'centro' => 'Queens Lab', 'regional' => 'Nueva York'],
            ['nombres' => 'Walter', 'apellidos' => 'White', 'genero' => 'masculino', 'centro' => 'Albuquerque Institute', 'regional' => 'Nuevo México'],
            ['nombres' => 'Eleven', 'apellidos' => 'Hopper', 'genero' => 'femenino', 'centro' => 'Hawkins Lab', 'regional' => 'Indiana'],
            ['nombres' => 'Bruce', 'apellidos' => 'Wayne', 'genero' => 'masculino', 'centro' => 'Wayne Manor', 'regional' => 'Gotham'],
            ['nombres' => 'Lois', 'apellidos' => 'Lane', 'genero' => 'femenino', 'centro' => 'Daily Planet', 'regional' => 'Metrópolis'],
            ['nombres' => 'Luke', 'apellidos' => 'Skywalker', 'genero' => 'masculino', 'centro' => 'Tatooine Base', 'regional' => 'Tatooine'],
            ['nombres' => 'Leia', 'apellidos' => 'Organa', 'genero' => 'femenino', 'centro' => 'Alderaan Embassy', 'regional' => 'Alderaan'],
            ['nombres' => 'Jon', 'apellidos' => 'Snow', 'genero' => 'masculino', 'centro' => 'Castle Black', 'regional' => 'Norte'],
            ['nombres' => 'Arya', 'apellidos' => 'Stark', 'genero' => 'femenino', 'centro' => 'Winterfell', 'regional' => 'Norte'],
            ['nombres' => 'Sherlock', 'apellidos' => 'Holmes', 'genero' => 'masculino', 'centro' => 'Baker Street', 'regional' => 'Londres'],
            ['nombres' => 'John', 'apellidos' => 'Watson', 'genero' => 'masculino', 'centro' => 'Baker Street', 'regional' => 'Londres'],
            ['nombres' => 'Marty', 'apellidos' => 'McFly', 'genero' => 'masculino', 'centro' => 'Hill Valley High', 'regional' => 'California'],
            ['nombres' => 'Emmett', 'apellidos' => 'Brown', 'genero' => 'masculino', 'centro' => 'Hill Valley Lab', 'regional' => 'California'],
            ['nombres' => 'Indiana', 'apellidos' => 'Jones', 'genero' => 'masculino', 'centro' => 'Marshall College', 'regional' => 'Illinois'],
            ['nombres' => 'Lara', 'apellidos' => 'Croft', 'genero' => 'femenino', 'centro' => 'Croft Manor', 'regional' => 'Inglaterra'],
            ['nombres' => 'James', 'apellidos' => 'Bond', 'genero' => 'masculino', 'centro' => 'MI6 Headquarters', 'regional' => 'Londres'],
            ['nombres' => 'Katniss', 'apellidos' => 'Everdeen', 'genero' => 'femenino', 'centro' => 'Distrito 12', 'regional' => 'Panem'],
            ['nombres' => 'Peeta', 'apellidos' => 'Mellark', 'genero' => 'masculino', 'centro' => 'Distrito 12', 'regional' => 'Panem'],
            ['nombres' => 'Frodo', 'apellidos' => 'Baggins', 'genero' => 'masculino', 'centro' => 'Bolsón Cerrado', 'regional' => 'La Comarca'],
            ['nombres' => 'Samwise', 'apellidos' => 'Gamgee', 'genero' => 'masculino', 'centro' => 'Bolsón Cerrado', 'regional' => 'La Comarca'],
            ['nombres' => 'Gandalf', 'apellidos' => 'Grey', 'genero' => 'masculino', 'centro' => 'Rivendel', 'regional' => 'Tierra Media'],
            ['nombres' => 'Aragorn', 'apellidos' => 'Elessar', 'genero' => 'masculino', 'centro' => 'Gondor House', 'regional' => 'Gondor'],
            ['nombres' => 'Neo', 'apellidos' => 'Anderson', 'genero' => 'masculino', 'centro' => 'The Matrix', 'regional' => 'Chicago'],
            ['nombres' => 'Trinity', 'apellidos' => 'Harris', 'genero' => 'femenino', 'centro' => 'Zion', 'regional' => 'Desierto'],
            ['nombres' => 'Morpheus', 'apellidos' => 'Jones', 'genero' => 'masculino', 'centro' => 'Zion', 'regional' => 'Desierto'],
            ['nombres' => 'John', 'apellidos' => 'Wick', 'genero' => 'masculino', 'centro' => 'Continental Hotel', 'regional' => 'Nueva York'],
            ['nombres' => 'Ellen', 'apellidos' => 'Ripley', 'genero' => 'femenino', 'centro' => 'Nostromo Hangar', 'regional' => 'Espacio'],
            ['nombres' => 'Darth', 'apellidos' => 'Vader', 'genero' => 'masculino', 'centro' => 'Estrella de la Muerte', 'regional' => 'Espacio'],
            ['nombres' => 'Han', 'apellidos' => 'Solo', 'genero' => 'masculino', 'centro' => 'Halcón Milenario', 'regional' => 'Espacio'],
            ['nombres' => 'Jean-Luc', 'apellidos' => 'Picard', 'genero' => 'masculino', 'centro' => 'USS Enterprise', 'regional' => 'Espacio'],
            ['nombres' => 'Spock', 'apellidos' => 'S', 'genero' => 'masculino', 'centro' => 'USS Enterprise', 'regional' => 'Espacio'],
            ['nombres' => 'Buffy', 'apellidos' => 'Summers', 'genero' => 'femenino', 'centro' => 'Sunnydale High', 'regional' => 'California'],
            ['nombres' => 'Willow', 'apellidos' => 'Rosenberg', 'genero' => 'femenino', 'centro' => 'Sunnydale High', 'regional' => 'California'],
            ['nombres' => 'Xena', 'apellidos' => 'Warrior', 'genero' => 'femenino', 'centro' => 'Amphipolis', 'regional' => 'Grecia'],
            ['nombres' => 'Jack', 'apellidos' => 'Sparrow', 'genero' => 'masculino', 'centro' => 'Isla Tortuga', 'regional' => 'Caribe'],
            ['nombres' => 'Elsa', 'apellidos' => 'de Arendelle', 'genero' => 'femenino', 'centro' => 'Castillo de Arendelle', 'regional' => 'Arendelle'],
            ['nombres' => 'Anna', 'apellidos' => 'de Arendelle', 'genero' => 'femenino', 'centro' => 'Castillo de Arendelle', 'regional' => 'Arendelle'],
            ['nombres' => 'Simba', 'apellidos' => 'Lion', 'genero' => 'masculino', 'centro' => 'Pride Lands', 'regional' => 'África'],
            ['nombres' => 'Nala', 'apellidos' => 'Lion', 'genero' => 'femenino', 'centro' => 'Pride Lands', 'regional' => 'África'],
            ['nombres' => 'Bob', 'apellidos' => 'Parr', 'genero' => 'masculino', 'centro' => 'Metroville', 'regional' => 'USA'],
            ['nombres' => 'Helen', 'apellidos' => 'Parr', 'genero' => 'femenino', 'centro' => 'Metroville', 'regional' => 'USA'],
            ['nombres' => 'Buzz', 'apellidos' => 'Lightyear', 'genero' => 'masculino', 'centro' => 'Star Command', 'regional' => 'Espacio'],
            ['nombres' => 'Woody', 'apellidos' => 'Pride', 'genero' => 'masculino', 'centro' => 'Rancho del Vaquero', 'regional' => 'California'],
            ['nombres' => 'Fox', 'apellidos' => 'Mulder', 'genero' => 'masculino', 'centro' => 'FBI Headquarters', 'regional' => 'Virginia'],
            ['nombres' => 'Dana', 'apellidos' => 'Scully', 'genero' => 'femenino', 'centro' => 'FBI Headquarters', 'regional' => 'Virginia'],
            ['nombres' => 'Rick', 'apellidos' => 'Grimes', 'genero' => 'masculino', 'centro' => 'Alexandria', 'regional' => 'Virginia'],
            ['nombres' => 'Daryl', 'apellidos' => 'Dixon', 'genero' => 'masculino', 'centro' => 'Alexandria', 'regional' => 'Virginia'],
            ['nombres' => 'Saul', 'apellidos' => 'Goodman', 'genero' => 'masculino', 'centro' => 'Better Call Saul', 'regional' => 'Albuquerque'],
            ['nombres' => 'Cersei', 'apellidos' => 'Lannister', 'genero' => 'femenino', 'centro' => 'King\'s Landing', 'regional' => 'Westeros'],
            ['nombres' => 'Jaime', 'apellidos' => 'Lannister', 'genero' => 'masculino', 'centro' => 'King\'s Landing', 'regional' => 'Westeros'],
            ['nombres' => 'Tyrion', 'apellidos' => 'Lannister', 'genero' => 'masculino', 'centro' => 'King\'s Landing', 'regional' => 'Westeros'],
            ['nombres' => 'Margaery', 'apellidos' => 'Tyrell', 'genero' => 'femenino', 'centro' => 'King\'s Landing', 'regional' => 'Westeros'],
            ['nombres' => 'Sansa', 'apellidos' => 'Stark', 'genero' => 'femenino', 'centro' => 'Winterfell', 'regional' => 'Norte'],
            ['nombres' => 'Brienne', 'apellidos' => 'of Tarth', 'genero' => 'femenino', 'centro' => 'Tarth', 'regional' => 'Occidente'],
            ['nombres' => 'Hodor', 'apellidos' => 'Hodor', 'genero' => 'masculino', 'centro' => 'Winterfell', 'regional' => 'Norte'],
            ['nombres' => 'Khal', 'apellidos' => 'Drogo', 'genero' => 'masculino', 'centro' => 'Mar Dothraki', 'regional' => 'Essos'],
            ['nombres' => 'Joffrey', 'apellidos' => 'Baratheon', 'genero' => 'masculino', 'centro' => 'King\'s Landing', 'regional' => 'Westeros'],
            ['nombres' => 'Yoda', 'apellidos' => 'Master', 'genero' => 'masculino', 'centro' => 'Dagobah', 'regional' => 'Espacio'],
            ['nombres' => 'Palpatine', 'apellidos' => 'Sidious', 'genero' => 'masculino', 'centro' => 'Coruscant', 'regional' => 'Espacio'],
            ['nombres' => 'Kylo', 'apellidos' => 'Ren', 'genero' => 'masculino', 'centro' => 'Starkiller Base', 'regional' => 'Espacio'],
            ['nombres' => 'Rey', 'apellidos' => 'Skywalker', 'genero' => 'femenino', 'centro' => 'Ahch-To', 'regional' => 'Espacio'],
            ['nombres' => 'Finn', 'apellidos' => 'FN-2187', 'genero' => 'masculino', 'centro' => 'Resistance Base', 'regional' => 'Espacio'],
            ['nombres' => 'Poe', 'apellidos' => 'Dameron', 'genero' => 'masculino', 'centro' => 'Resistance Base', 'regional' => 'Espacio'],
            ['nombres' => 'Harley', 'apellidos' => 'Quinn', 'genero' => 'femenino', 'centro' => 'Arkham Asylum', 'regional' => 'Gotham'],
            ['nombres' => 'Joker', 'apellidos' => 'Black', 'genero' => 'masculino', 'centro' => 'Arkham Asylum', 'regional' => 'Gotham'],
            ['nombres' => 'Clark', 'apellidos' => 'Kent', 'genero' => 'masculino', 'centro' => 'Daily Planet', 'regional' => 'Metrópolis'],
            ['nombres' => 'Diana', 'apellidos' => 'Prince', 'genero' => 'femenino', 'centro' => 'Themyscira', 'regional' => 'Grecia'],
            ['nombres' => 'Arthur', 'apellidos' => 'Curry', 'genero' => 'masculino', 'centro' => 'Atlantis', 'regional' => 'Océano'],
            ['nombres' => 'T\'Challa', 'apellidos' => 'Udaku', 'genero' => 'masculino', 'centro' => 'Wakanda', 'regional' => 'África'],
            ['nombres' => 'Shuri', 'apellidos' => 'Udaku', 'genero' => 'femenino', 'centro' => 'Wakanda', 'regional' => 'África'],
            ['nombres' => 'Stephen', 'apellidos' => 'Strange', 'genero' => 'masculino', 'centro' => 'Sanctum Sanctorum', 'regional' => 'Nueva York'],
            ['nombres' => 'Wanda', 'apellidos' => 'Maximoff', 'genero' => 'femenino', 'centro' => 'Westview', 'regional' => 'Nueva Jersey'],
            ['nombres' => 'Vision', 'apellidos' => 'Avenger', 'genero' => 'masculino', 'centro' => 'Westview', 'regional' => 'Nueva Jersey'],
            ['nombres' => 'Nick', 'apellidos' => 'Fury', 'genero' => 'masculino', 'centro' => 'SHIELD Tower', 'regional' => 'Nueva York'],
            ['nombres' => 'Loki', 'apellidos' => 'Laufeyson', 'genero' => 'masculino', 'centro' => 'Asgard', 'regional' => 'Espacio'],
            ['nombres' => 'Thor', 'apellidos' => 'Odinson', 'genero' => 'masculino', 'centro' => 'Asgard', 'regional' => 'Espacio'],
            ['nombres' => 'Natasha', 'apellidos' => 'Romanoff', 'genero' => 'femenino', 'centro' => 'SHIELD Tower', 'regional' => 'Nueva York'],
            ['nombres' => 'James', 'apellidos' => 'Rhodes', 'genero' => 'masculino', 'centro' => 'SHIELD Tower', 'regional' => 'Nueva York'],
            ['nombres' => 'Peter', 'apellidos' => 'Quill', 'genero' => 'masculino', 'centro' => 'Milano', 'regional' => 'Espacio'],
            ['nombres' => 'Gamora', 'apellidos' => 'Zen', 'genero' => 'femenino', 'centro' => 'Milano', 'regional' => 'Espacio'],
            ['nombres' => 'Rocket', 'apellidos' => 'Raccoon', 'genero' => 'masculino', 'centro' => 'Milano', 'regional' => 'Espacio'],
            ['nombres' => 'Groot', 'apellidos' => 'Tree', 'genero' => 'masculino', 'centro' => 'Milano', 'regional' => 'Espacio'],
            ['nombres' => 'Drax', 'apellidos' => 'The Destroyer', 'genero' => 'masculino', 'centro' => 'Milano', 'regional' => 'Espacio'],
            ['nombres' => 'Din', 'apellidos' => 'Djarin', 'genero' => 'masculino', 'centro' => 'Navarro', 'regional' => 'Galaxia'],
            ['nombres' => 'Grogu', 'apellidos' => 'The Child', 'genero' => 'masculino', 'centro' => 'Navarro', 'regional' => 'Galaxia'],
            ['nombres' => 'Sheldon', 'apellidos' => 'Cooper', 'genero' => 'masculino', 'centro' => 'Caltech', 'regional' => 'Pasadena'],
            ['nombres' => 'Leonard', 'apellidos' => 'Hofstadter', 'genero' => 'masculino', 'centro' => 'Caltech', 'regional' => 'Pasadena'],
            ['nombres' => 'Penny', 'apellidos' => 'Hofstadter', 'genero' => 'femenino', 'centro' => 'Caltech', 'regional' => 'Pasadena'],
            ['nombres' => 'Howard', 'apellidos' => 'Wolowitz', 'genero' => 'masculino', 'centro' => 'Caltech', 'regional' => 'Pasadena'],
            ['nombres' => 'Raj', 'apellidos' => 'Koothrappali', 'genero' => 'masculino', 'centro' => 'Caltech', 'regional' => 'Pasadena'],
            ['nombres' => 'Michael', 'apellidos' => 'Scott', 'genero' => 'masculino', 'centro' => 'Dunder Mifflin', 'regional' => 'Scranton'],
            ['nombres' => 'Jim', 'apellidos' => 'Halpert', 'genero' => 'masculino', 'centro' => 'Dunder Mifflin', 'regional' => 'Scranton'],
            ['nombres' => 'Pam', 'apellidos' => 'Beesly', 'genero' => 'femenino', 'centro' => 'Dunder Mifflin', 'regional' => 'Scranton'],
            ['nombres' => 'Dwight', 'apellidos' => 'Schrute', 'genero' => 'masculino', 'centro' => 'Schrute Farms', 'regional' => 'Scranton'],
            ['nombres' => 'Tony', 'apellidos' => 'Soprano', 'genero' => 'masculino', 'centro' => 'Bada Bing', 'regional' => 'Nueva Jersey'],
            ['nombres' => 'Don', 'apellidos' => 'Draper', 'genero' => 'masculino', 'centro' => 'Sterling Cooper', 'regional' => 'Nueva York'],
            ['nombres' => 'Walter', 'apellidos' => 'Sobchak', 'genero' => 'masculino', 'centro' => 'Big Lebowski House', 'regional' => 'Los Ángeles'],
            ['nombres' => 'The', 'apellidos' => 'Dude', 'genero' => 'masculino', 'centro' => 'Big Lebowski House', 'regional' => 'Los Ángeles'],
            ['nombres' => 'Mia', 'apellidos' => 'Wallace', 'genero' => 'femenino', 'centro' => 'Jack Rabbit Slim\'s', 'regional' => 'Los Ángeles'],
            ['nombres' => 'Vincent', 'apellidos' => 'Vega', 'genero' => 'masculino', 'centro' => 'Jack Rabbit Slim\'s', 'regional' => 'Los Ángeles'],
            ['nombres' => 'Jack', 'apellidos' => 'Dawson', 'genero' => 'masculino', 'centro' => 'Titanic', 'regional' => 'Atlántico'],
            ['nombres' => 'Rose', 'apellidos' => 'DeWitt Bukater', 'genero' => 'femenino', 'centro' => 'Titanic', 'regional' => 'Atlántico'],
            ['nombres' => 'Bronn', 'apellidos' => 'of the Blackwater', 'genero' => 'masculino', 'centro' => 'King\'s Landing', 'regional' => 'Westeros'],
            ['nombres' => 'Samwell', 'apellidos' => 'Tarly', 'genero' => 'masculino', 'centro' => 'Castle Black', 'regional' => 'Norte'],
            ['nombres' => 'Catelyn', 'apellidos' => 'Stark', 'genero' => 'femenino', 'centro' => 'Winterfell', 'regional' => 'Norte'],
            ['nombres' => 'Petyr', 'apellidos' => 'Baelish', 'genero' => 'masculino', 'centro' => 'Littlefinger Keep', 'regional' => 'Westeros'],
            ['nombres' => 'Varys', 'apellidos' => 'the Spider', 'genero' => 'masculino', 'centro' => 'King\'s Landing', 'regional' => 'Westeros'],
            ['nombres' => 'Michael', 'apellidos' => 'Corleone', 'genero' => 'masculino', 'centro' => 'Corleone Estate', 'regional' => 'Sicilia'],
            ['nombres' => 'Vito', 'apellidos' => 'Corleone', 'genero' => 'masculino', 'centro' => 'Corleone Estate', 'regional' => 'Sicilia'],
            ['nombres' => 'Tony', 'apellidos' => 'Montana', 'genero' => 'masculino', 'centro' => 'Scarface Mansion', 'regional' => 'Miami'],
            ['nombres' => 'Rick', 'apellidos' => 'Deckard', 'genero' => 'masculino', 'centro' => 'Los Ángeles Police', 'regional' => 'Los Ángeles'],
            ['nombres' => 'Sarah', 'apellidos' => 'Connor', 'genero' => 'femenino', 'centro' => 'Resistance Bunker', 'regional' => 'California'],
            ['nombres' => 'John', 'apellidos' => 'Connor', 'genero' => 'masculino', 'centro' => 'Resistance Bunker', 'regional' => 'California'],
            ['nombres' => 'Kyle', 'apellidos' => 'Reese', 'genero' => 'masculino', 'centro' => 'Resistance Bunker', 'regional' => 'California'],
            ['nombres' => 'Lilo', 'apellidos' => 'Pelekai', 'genero' => 'femenino', 'centro' => 'Kauai', 'regional' => 'Hawai'],
            ['nombres' => 'Stitch', 'apellidos' => 'Experiment 626', 'genero' => 'masculino', 'centro' => 'Kauai', 'regional' => 'Hawai'],
            ['nombres' => 'Mulan', 'apellidos' => 'Fa', 'genero' => 'femenino', 'centro' => 'Palacio Imperial', 'regional' => 'China'],
            ['nombres' => 'Mushu', 'apellidos' => 'Dragon', 'genero' => 'masculino', 'centro' => 'Palacio Imperial', 'regional' => 'China'],
            ['nombres' => 'Boba', 'apellidos' => 'Fett', 'genero' => 'masculino', 'centro' => 'Tatooine', 'regional' => 'Espacio'],
            ['nombres' => 'Obi-Wan', 'apellidos' => 'Kenobi', 'genero' => 'masculino', 'centro' => 'Tatooine', 'regional' => 'Espacio'],
            ['nombres' => 'Anakin', 'apellidos' => 'Skywalker', 'genero' => 'masculino', 'centro' => 'Tatooine', 'regional' => 'Espacio'],
            ['nombres' => 'Padmé', 'apellidos' => 'Amidala', 'genero' => 'femenino', 'centro' => 'Naboo', 'regional' => 'Espacio'],
            ['nombres' => 'Mal', 'apellidos' => 'Reynolds', 'genero' => 'masculino', 'centro' => 'Serenity', 'regional' => 'Espacio'],
            ['nombres' => 'Zoe', 'apellidos' => 'Washburne', 'genero' => 'femenino', 'centro' => 'Serenity', 'regional' => 'Espacio'],
            ['nombres' => 'Jayne', 'apellidos' => 'Cobb', 'genero' => 'masculino', 'centro' => 'Serenity', 'regional' => 'Espacio'],
            ['nombres' => 'Inara', 'apellidos' => 'Serra', 'genero' => 'femenino', 'centro' => 'Serenity', 'regional' => 'Espacio'],
            ['nombres' => 'Simon', 'apellidos' => 'Tam', 'genero' => 'masculino', 'centro' => 'Serenity', 'regional' => 'Espacio'],
            ['nombres' => 'Kaylee', 'apellidos' => 'Frye', 'genero' => 'femenino', 'centro' => 'Serenity', 'regional' => 'Espacio'],
            ['nombres' => 'River', 'apellidos' => 'Tam', 'genero' => 'femenino', 'centro' => 'Serenity', 'regional' => 'Espacio'],
            ['nombres' => 'Doctor', 'apellidos' => 'Who', 'genero' => 'masculino', 'centro' => 'TARDIS', 'regional' => 'Reino Unido'],
            ['nombres' => 'Clara', 'apellidos' => 'Oswald', 'genero' => 'femenino', 'centro' => 'TARDIS', 'regional' => 'Reino Unido'],
            ['nombres' => 'Amy', 'apellidos' => 'Pond', 'genero' => 'femenino', 'centro' => 'TARDIS', 'regional' => 'Reino Unido'],
            ['nombres' => 'Rory', 'apellidos' => 'Williams', 'genero' => 'masculino', 'centro' => 'TARDIS', 'regional' => 'Reino Unido'],
            ['nombres' => 'Ezio', 'apellidos' => 'Auditore', 'genero' => 'masculino', 'centro' => 'Firenze', 'regional' => 'Italia'],
            ['nombres' => 'Geralt', 'apellidos' => 'of Rivia', 'genero' => 'masculino', 'centro' => 'Kaer Morhen', 'regional' => 'Temeria'],
            ['nombres' => 'Ciri', 'apellidos' => 'Stregobor', 'genero' => 'femenino', 'centro' => 'Kaer Morhen', 'regional' => 'Temeria'],
            ['nombres' => 'Yennefer', 'apellidos' => 'of Vengerberg', 'genero' => 'femenino', 'centro' => 'Vengerberg', 'regional' => 'Temeria'],
            ['nombres' => 'Maximus', 'apellidos' => 'Decimus', 'genero' => 'masculino', 'centro' => 'Roma', 'regional' => 'Imperio Romano'],
            ['nombres' => 'Furiosa', 'apellidos' => 'Nux', 'genero' => 'femenino', 'centro' => 'Citadel', 'regional' => 'Australia'],
            ['nombres' => 'Alice', 'apellidos' => 'Kingsleigh', 'genero' => 'femenino', 'centro' => 'Wonderland', 'regional' => 'Reino Unido'],
            ['nombres' => 'Mad', 'apellidos' => 'Hatter', 'genero' => 'masculino', 'centro' => 'Wonderland', 'regional' => 'Reino Unido'],
            ['nombres' => 'Captain', 'apellidos' => 'Hook', 'genero' => 'masculino', 'centro' => 'Neverland', 'regional' => 'Caribe'],
            ['nombres' => 'Peter', 'apellidos' => 'Pan', 'genero' => 'masculino', 'centro' => 'Neverland', 'regional' => 'Caribe'],
            ['nombres' => 'Lisbeth', 'apellidos' => 'Salander', 'genero' => 'femenino', 'centro' => 'Stockholm', 'regional' => 'Suecia'],
            ['nombres' => 'Hannibal', 'apellidos' => 'Lecter', 'genero' => 'masculino', 'centro' => 'Baltimore State Hospital', 'regional' => 'USA'],
            ['nombres' => 'Clarice', 'apellidos' => 'Starling', 'genero' => 'femenino', 'centro' => 'FBI Academy', 'regional' => 'USA'],
            ['nombres' => 'John', 'apellidos' => 'McClane', 'genero' => 'masculino', 'centro' => 'Nakatomi Plaza', 'regional' => 'Los Ángeles'],
        ];

        $tipos = ['instructor', 'aprendiz', 'visitante'];
        $tiposSangre = ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'];
        $fotoMap = [
            'Tony Stark' => 'https://upload.wikimedia.org/wikipedia/en/e/e0/Iron_Man_Infobox.jpg',
            'Daenerys Targaryen' => 'https://upload.wikimedia.org/wikipedia/en/1/1b/Daenerys_Targaryen.jpg',
            'Hermione Granger' => 'https://upload.wikimedia.org/wikipedia/en/d/d3/Hermione_Granger_poster.jpg',
            'Peter Parker' => 'https://upload.wikimedia.org/wikipedia/en/0/0c/Spider-Man2002poster.jpg',
            'Walter White' => 'https://upload.wikimedia.org/wikipedia/en/6/6e/Walter_White_S5B.png',
            'Eleven Hopper' => 'https://upload.wikimedia.org/wikipedia/en/c/c9/Eleven_%28Stranger_Things%29.png',
            'Bruce Wayne' => 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8d/Ben_Affleck_as_Batman.png/220px-Ben_Affleck_as_Batman.png',
            'Lois Lane' => 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7e/Lois_Lane.jpg/220px-Lois_Lane.jpg',
            'Luke Skywalker' => 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6c/Luke_Skywalker.png/220px-Luke_Skywalker.png',
            'Leia Organa' => 'https://upload.wikimedia.org/wikipedia/en/6/6a/Leia_Organa.png',
            'Jon Snow' => 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8d/Kit_Harington_as_Jon_Snow.jpg/220px-Kit_Harington_as_Jon_Snow.jpg',
            'Arya Stark' => 'https://upload.wikimedia.org/wikipedia/en/thumb/3/34/Arya_Stark_%28GOT%29.jpeg/220px-Arya_Stark_%28GOT%29.jpeg',
            'Sherlock Holmes' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Benedict_Cumberbatch_2014.jpg/250px-Benedict_Cumberbatch_2014.jpg',
            'John Watson' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Martin_Freeman_at_THE_HOBBIT_BOTFA.jpg/220px-Martin_Freeman_at_THE_HOBBIT_BOTFA.jpg',
            'Marty McFly' => 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5e/Marty_McFly.png/220px-Marty_McFly.png',
            'Emmett Brown' => 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c0/Christopher_Lloyd_%28cropped%29.jpg/220px-Christopher_Lloyd_%28cropped%29.jpg',
            'Indiana Jones' => 'https://upload.wikimedia.org/wikipedia/en/thumb/7/71/Harrison_Ford_as_Indiana_Jones.jpg/220px-Harrison_Ford_as_Indiana_Jones.jpg',
            'Lara Croft' => 'https://upload.wikimedia.org/wikipedia/en/thumb/7/71/Lara_Croft_Tomb_Raider.png/220px-Lara_Croft_Tomb_Raider.png',
            'James Bond' => 'https://upload.wikimedia.org/wikipedia/en/thumb/0/00/Sean_Connery_as_James_Bond.jpg/220px-Sean_Connery_as_James_Bond.jpg',
            'Katniss Everdeen' => 'https://upload.wikimedia.org/wikipedia/en/thumb/7/74/Katniss_Everdeen.png/220px-Katniss_Everdeen.png',
            'Peeta Mellark' => 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b3/Peeta_Mellark.png/220px-Peeta_Mellark.png',
            'Frodo Baggins' => 'https://upload.wikimedia.org/wikipedia/en/thumb/5/52/Elijah_Wood_as_Frodo_Baggins.jpg/220px-Elijah_Wood_as_Frodo_Baggins.jpg',
            'Samwise Gamgee' => 'https://upload.wikimedia.org/wikipedia/en/thumb/9/99/Sean_Astin_as_Samwise_Gamgee.jpg/220px-Sean_Astin_as_Samwise_Gamgee.jpg',
            'Gandalf Grey' => 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e1/Gandalf_the_Grey.jpg/220px-Gandalf_the_Grey.jpg',
            'Aragorn Elessar' => 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5e/Aragorn300ppx.jpg/220px-Aragorn300ppx.jpg',
            'Neo Anderson' => 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c0/NeoTheMatrix.jpg/220px-NeoTheMatrix.jpg',
            'Trinity Harris' => 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Trinity_%28The_Matrix%29.jpg/220px-Trinity_%28The_Matrix%29.jpg',
            'Morpheus Jones' => 'https://upload.wikimedia.org/wikipedia/en/thumb/5/50/Morpheus_%28The_Matrix%29.jpg/220px-Morpheus_%28The_Matrix%29.jpg',
            'John Wick' => 'https://upload.wikimedia.org/wikipedia/en/thumb/3/34/John_Wick_Poster.jpg/220px-John_Wick_Poster.jpg',
            'Ellen Ripley' => 'https://upload.wikimedia.org/wikipedia/en/thumb/2/27/Ellen_Ripley_%28Alien%29.jpg/220px-Ellen_Ripley_%28Alien%29.jpg',
            'Darth Vader' => 'https://upload.wikimedia.org/wikipedia/en/thumb/7/76/Darth_Vader.jpg/220px-Darth_Vader.jpg',
            'Han Solo' => 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7e/Han_Solo.png/220px-Han_Solo.png',
            'Jean-Luc Picard' => 'https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Jean-Luc_Picard.jpg/220px-Jean-Luc_Picard.jpg',
            'Spock S' => 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2b/Spock.jpg/220px-Spock.jpg',
            'Buffy Summers' => 'https://upload.wikimedia.org/wikipedia/en/thumb/8/88/Buffy_The_Vampire_Slayer1.png/220px-Buffy_The_Vampire_Slayer1.png',
            'Willow Rosenberg' => 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Willow_Rosenberg.png/220px-Willow_Rosenberg.png',
            'Xena Warrior' => 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e0/Xena_Warrior_Princess.jpg/220px-Xena_Warrior_Princess.jpg',
            'Jack Sparrow' => 'https://upload.wikimedia.org/wikipedia/en/thumb/6/65/Johnny_Depp_as_Captain_Jack_Sparrow.jpg/220px-Johnny_Depp_as_Captain_Jack_Sparrow.jpg',
            'Elsa de Arendelle' => 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8f/Elsa_%28Disney_Frozen%29.png/220px-Elsa_%28Disney_Frozen%29.png',
            'Anna de Arendelle' => 'https://upload.wikimedia.org/wikipedia/en/thumb/8/88/Anna_%28Disney_Frozen%29.png/220px-Anna_%28Disney_Frozen%29.png',
            'Simba Lion' => 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0f/Simba_%28Disney%29.png/220px-Simba_%28Disney%29.png',
            'Nala Lion' => 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f4/Nala_%28Disney%29.png/220px-Nala_%28Disney%29.png',
            'Bob Parr' => 'https://upload.wikimedia.org/wikipedia/en/thumb/5/50/Bob_Parr.png/220px-Bob_Parr.png',
            'Helen Parr' => 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a6/Helen_Parr.png/220px-Helen_Parr.png',
            'Buzz Lightyear' => 'https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Buzz_Lightyear.png/220px-Buzz_Lightyear.png',
            'Woody Pride' => 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Woody.png/220px-Woody.png',
            'Fox Mulder' => 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b2/David_Duchovny_as_Fox_Mulder.jpg/220px-David_Duchovny_as_Fox_Mulder.jpg',
            'Dana Scully' => 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e4/Gillian_Anderson_as_Dana_Scully.jpg/220px-Gillian_Anderson_as_Dana_Scully.jpg',
            'Rick Grimes' => 'https://upload.wikimedia.org/wikipedia/en/thumb/f/fd/Rick_Grimes.jpg/220px-Rick_Grimes.jpg',
            'Daryl Dixon' => 'https://upload.wikimedia.org/wikipedia/en/thumb/1/14/Daryl_Dixon.jpg/220px-Daryl_Dixon.jpg',
            'Saul Goodman' => 'https://upload.wikimedia.org/wikipedia/en/thumb/9/92/Saul_Goodman.jpg/220px-Saul_Goodman.jpg',
            'Cersei Lannister' => 'https://upload.wikimedia.org/wikipedia/en/thumb/8/82/Cersei_Lannister.jpg/220px-Cersei_Lannister.jpg',
            'Jaime Lannister' => 'https://upload.wikimedia.org/wikipedia/en/thumb/9/92/Jaime_Lannister.jpg/220px-Jaime_Lannister.jpg',
            'Tyrion Lannister' => 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7b/Tyrion_Lannister.jpg/220px-Tyrion_Lannister.jpg',
            'Margaery Tyrell' => 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Margaery_Tyrell.jpg/220px-Margaery_Tyrell.jpg',
            'Sansa Stark' => 'https://upload.wikimedia.org/wikipedia/en/thumb/4/47/Sansa_Stark.jpg/220px-Sansa_Stark.jpg',
            'Brienne of Tarth' => 'https://upload.wikimedia.org/wikipedia/en/thumb/8/81/Brienne_of_Tarth.jpg/220px-Brienne_of_Tarth.jpg',
            'Hodor Hodor' => 'https://upload.wikimedia.org/wikipedia/en/thumb/1/10/Hodor.jpg/220px-Hodor.jpg',
            'Khal Drogo' => 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8f/Khal_Drogo.jpg/220px-Khal_Drogo.jpg',
            'Joffrey Baratheon' => 'https://upload.wikimedia.org/wikipedia/en/thumb/1/10/Joffrey_Baratheon.jpg/220px-Joffrey_Baratheon.jpg',
            'Yoda Master' => 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c5/Yoda_Empire.jpg/220px-Yoda_Empire.jpg',
            'Palpatine Sidious' => 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6d/Emperor-Palpatine.jpg/220px-Emperor-Palpatine.jpg',
            'Kylo Ren' => 'https://upload.wikimedia.org/wikipedia/en/thumb/7/77/Kylo_Ren.png/220px-Kylo_Ren.png',
            'Rey Skywalker' => 'https://upload.wikimedia.org/wikipedia/en/thumb/1/14/Rey_%28Star_Wars%29.png/220px-Rey_%28Star_Wars%29.png',
            'Finn FN-2187' => 'https://upload.wikimedia.org/wikipedia/en/thumb/4/44/Finn_%28Star_Wars%29.png/220px-Finn_%28Star_Wars%29.png',
            'Poe Dameron' => 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e2/Poe_Dameron.png/220px-Poe_Dameron.png',
            'Harley Quinn' => 'https://upload.wikimedia.org/wikipedia/en/thumb/2/29/Harley_Quinn_%28DC_Comics%29.png/220px-Harley_Quinn_%28DC_Comics%29.png',
            'Joker Black' => 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5a/Joker_%28The_Dark_Knight%29.jpg/220px-Joker_%28The_Dark_Knight%29.jpg',
            'Clark Kent' => 'https://upload.wikimedia.org/wikipedia/en/thumb/1/1b/Superman_%28Henry_Cavill%29.jpg/220px-Superman_%28Henry_Cavill%29.jpg',
            'Diana Prince' => 'https://upload.wikimedia.org/wikipedia/en/thumb/e/ed/Wonder_Woman_%282017_film%29.jpg/220px-Wonder_Woman_%282017_film%29.jpg',
            'Arthur Curry' => 'https://upload.wikimedia.org/wikipedia/en/thumb/3/33/Aquaman_%28Jason_Momoa%29.jpg/220px-Aquaman_%28Jason_Momoa%29.jpg',
            'T\'Challa Udaku' => 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0f/Black_Panther_mcu_poster.jpg/220px-Black_Panther_mcu_poster.jpg',
            'Shuri Udaku' => 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7f/Shuri_%28Marvel%29.jpg/220px-Shuri_%28Marvel%29.jpg',
            'Stephen Strange' => 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c7/Doctor_Strange_poster.jpg/220px-Doctor_Strange_poster.jpg',
            'Wanda Maximoff' => 'https://upload.wikimedia.org/wikipedia/en/thumb/9/98/WandaVision_poster.jpg/220px-WandaVision_poster.jpg',
            'Vision Avenger' => 'https://upload.wikimedia.org/wikipedia/en/thumb/3/36/Vision_%28Marvel%29.png/220px-Vision_%28Marvel%29.png',
            'Nick Fury' => 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/Nick_Fury.png/220px-Nick_Fury.png',
            'Loki Laufeyson' => 'https://upload.wikimedia.org/wikipedia/en/thumb/1/18/Loki_poster.jpg/220px-Loki_poster.jpg',
            'Thor Odinson' => 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7d/Thor_ragnarok_poster.jpg/220px-Thor_ragnarok_poster.jpg',
            'Natasha Romanoff' => 'https://upload.wikimedia.org/wikipedia/en/thumb/7/76/Black_Widow_2021_poster.jpg/220px-Black_Widow_2021_poster.jpg',
            'James Rhodes' => 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/War_Machine.jpg/220px-War_Machine.jpg',
            'Peter Quill' => 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5a/Chris_Pratts_Star-Lord.jpg/220px-Chris_Pratts_Star-Lord.jpg',
            'Gamora Zen' => 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0d/Gamora.jpg/220px-Gamora.jpg',
            'Rocket Raccoon' => 'https://upload.wikimedia.org/wikipedia/en/thumb/7/79/Rocket_Raccoon.png/220px-Rocket_Raccoon.png',
            'Groot Tree' => 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4e/Groot_%28Marvel%29.png/220px-Groot_%28Marvel%29.png',
            'Drax The Destroyer' => 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cd/Drax.png/220px-Drax.png',
            'Din Djarin' => 'https://upload.wikimedia.org/wikipedia/en/thumb/0/08/The_Mandalorian.png/220px-The_Mandalorian.png',
            'Grogu The Child' => 'https://upload.wikimedia.org/wikipedia/en/thumb/1/10/Grogu.png/220px-Grogu.png',
            'Sheldon Cooper' => 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f8/Jim_Parsons_as_Sheldon_Cooper.jpg/220px-Jim_Parsons_as_Sheldon_Cooper.jpg',
            'Leonard Hofstadter' => 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4a/Johnny_Galecki_as_Leonard_Hofstadter.jpg/220px-Johnny_Galecki_as_Leonard_Hofstadter.jpg',
            'Penny Hofstadter' => 'https://upload.wikimedia.org/wikipedia/en/thumb/6/67/Kaley_Cuoco_as_Penny.png/220px-Kaley_Cuoco_as_Penny.png',
            'Howard Wolowitz' => 'https://upload.wikimedia.org/wikipedia/en/thumb/1/1a/Simon_Helberg_as_Howard_Wolowitz.jpg/220px-Simon_Helberg_as_Howard_Wolowitz.jpg',
            'Raj Koothrappali' => 'https://upload.wikimedia.org/wikipedia/en/thumb/e/ec/Kunal_Nayyar_as_Raj_Koothrappali.jpg/220px-Kunal_Nayyar_as_Raj_Koothrappali.jpg',
            'Michael Scott' => 'https://upload.wikimedia.org/wikipedia/en/thumb/3/32/Michael_Scott_%28The_Office%29.png/220px-Michael_Scott_%28The_Office%29.png',
            'Jim Halpert' => 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Jim_Halpert_%28The_Office%29.png/220px-Jim_Halpert_%28The_Office%29.png',
            'Pam Beesly' => 'https://upload.wikimedia.org/wikipedia/en/thumb/1/1c/Pam_Beesly.png/220px-Pam_Beesly.png',
            'Dwight Schrute' => 'https://upload.wikimedia.org/wikipedia/en/thumb/7/77/Dwight_Schrute.png/220px-Dwight_Schrute.png',
            'Tony Soprano' => 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4f/Tony_Soprano.png/220px-Tony_Soprano.png',
            'Don Draper' => 'https://upload.wikimedia.org/wikipedia/en/thumb/2/28/Don_Draper_SW.png/220px-Don_Draper_SW.png',
            'Walter Sobchak' => 'https://upload.wikimedia.org/wikipedia/en/thumb/4/40/Walter_Sobchak.png/220px-Walter_Sobchak.png',
            'The Dude' => 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d5/Jeff_Bridges_as_The_Dude.jpg/220px-Jeff_Bridges_as_The_Dude.jpg',
            'Mia Wallace' => 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e0/Mia_Wallace.png/220px-Mia_Wallace.png',
            'Vincent Vega' => 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5a/Vincent_Vega.png/220px-Vincent_Vega.png',
            'Jack Dawson' => 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8d/Jack_Dawson.png/220px-Jack_Dawson.png',
            'Rose DeWitt Bukater' => 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d1/Rose_DeWitt_Bukater.png/220px-Rose_DeWitt_Bukater.png',
            'Bronn of the Blackwater' => 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b2/Bronn_%28GoT%29.jpg/220px-Bronn_%28GoT%29.jpg',
            'Samwell Tarly' => 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c6/Samwell_Tarly.jpg/220px-Samwell_Tarly.jpg',
            'Catelyn Stark' => 'https://upload.wikimedia.org/wikipedia/en/thumb/6/69/Catelyn_Stark.jpg/220px-Catelyn_Stark.jpg',
            'Petyr Baelish' => 'https://upload.wikimedia.org/wikipedia/en/thumb/6/69/Petyr_Baelish.jpg/220px-Petyr_Baelish.jpg',
            'Varys the Spider' => 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a3/Varys.jpg/220px-Varys.jpg',
            'Michael Corleone' => 'https://upload.wikimedia.org/wikipedia/en/thumb/2/25/Michael_Corleone.png/220px-Michael_Corleone.png',
            'Vito Corleone' => 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Vito_Corleone.png/220px-Vito_Corleone.png',
            'Tony Montana' => 'https://upload.wikimedia.org/wikipedia/en/thumb/1/1f/Al_Pacino_as_Tony_Montana.jpg/220px-Al_Pacino_as_Tony_Montana.jpg',
            'Rick Deckard' => 'https://upload.wikimedia.org/wikipedia/en/thumb/7/76/Rick_Deckard.png/220px-Rick_Deckard.png',
            'Sarah Connor' => 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d4/Sarah_Connor.png/220px-Sarah_Connor.png',
            'John Connor' => 'https://upload.wikimedia.org/wikipedia/en/thumb/4/43/John_Connor.png/220px-John_Connor.png',
            'Kyle Reese' => 'https://upload.wikimedia.org/wikipedia/en/thumb/6/66/Kyle_Reese.png/220px-Kyle_Reese.png',
            'Lilo Pelekai' => 'https://upload.wikimedia.org/wikipedia/en/thumb/e/ee/Lilo_Pelekai.png/220px-Lilo_Pelekai.png',
            'Stitch Experiment 626' => 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d0/Stitch_%28Disney%29.png/220px-Stitch_%28Disney%29.png',
            'Mulan Fa' => 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2d/Mulan_%28Disney_character%29.png/220px-Mulan_%28Disney_character%29.png',
            'Mushu Dragon' => 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4a/Mushu.png/220px-Mushu.png',
            'Boba Fett' => 'https://upload.wikimedia.org/wikipedia/en/thumb/6/67/Boba_Fett.png/220px-Boba_Fett.png',
            'Obi-Wan Kenobi' => 'https://upload.wikimedia.org/wikipedia/en/thumb/0/09/Obi-Wan_Kenobi.png/220px-Obi-Wan_Kenobi.png',
            'Anakin Skywalker' => 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e8/Anakin_Skywalker.png/220px-Anakin_Skywalker.png',
            'Padmé Amidala' => 'https://upload.wikimedia.org/wikipedia/en/thumb/2/20/Padm%C3%A9_Amidala.png/220px-Padm%C3%A9_Amidala.png',
            'Mal Reynolds' => 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3d/Mal_Reynolds.png/220px-Mal_Reynolds.png',
            'Zoe Washburne' => 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4d/Zoe_Washburne.png/220px-Zoe_Washburne.png',
            'Jayne Cobb' => 'https://upload.wikimedia.org/wikipedia/en/thumb/0/04/Jayne_Cobb.png/220px-Jayne_Cobb.png',
            'Inara Serra' => 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a9/Inara_Serra.png/220px-Inara_Serra.png',
            'Simon Tam' => 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8b/Simon_Tam.png/220px-Simon_Tam.png',
            'Kaylee Frye' => 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f8/Kaylee_Frye.png/220px-Kaylee_Frye.png',
            'River Tam' => 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0f/River_Tam.png/220px-River_Tam.png',
            'Doctor Who' => 'https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Doctor_Who_Tardis.jpg/220px-Doctor_Who_Tardis.jpg',
            'Clara Oswald' => 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e8/Clara_Oswald.png/220px-Clara_Oswald.png',
            'Amy Pond' => 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9f/Amy_Pond.png/220px-Amy_Pond.png',
            'Rory Williams' => 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a6/Rory_Williams.png/220px-Rory_Williams.png',
            'Ezio Auditore' => 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f6/Ezio_Auditore.png/220px-Ezio_Auditore.png',
            'Geralt of Rivia' => 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6f/Geralt_of_Rivia.png/220px-Geralt_of_Rivia.png',
            'Ciri Stregobor' => 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5c/Ciri.png/220px-Ciri.png',
            'Yennefer of Vengerberg' => 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f7/Yennefer.png/220px-Yennefer.png',
            'Maximus Decimus' => 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0a/Maximus_Decimus_Meridius.png/220px-Maximus_Decimus_Meridius.png',
            'Furiosa Nux' => 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e3/Furiosa.png/220px-Furiosa.png',
            'Alice Kingsleigh' => 'https://upload.wikimedia.org/wikipedia/en/thumb/8/82/Alice_in_Wonderland_%28_Imagin_7%29.jpg/220px-Alice_in_Wonderland_%28_Imagin_7%29.jpg',
            'Mad Hatter' => 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3d/Mad_Hatter_%28Johnny_Depp%29.png/220px-Mad_Hatter_%28Johnny_Depp%29.png',
            'Captain Hook' => 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c5/Captain_Hook.png/220px-Captain_Hook.png',
            'Peter Pan' => 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6c/Peter_Pan.png/220px-Peter_Pan.png',
            'Lisbeth Salander' => 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e7/Lisbeth_Salander.jpg/220px-Lisbeth_Salander.jpg',
            'Hannibal Lecter' => 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2c/Anthony_Hopkins_as_Hannibal_Lecter.jpg/220px-Anthony_Hopkins_as_Hannibal_Lecter.jpg',
            'Clarice Starling' => 'https://upload.wikimedia.org/wikipedia/en/thumb/1/1b/Jodie_Foster_as_Clarice_Starling.jpg/220px-Jodie_Foster_as_Clarice_Starling.jpg',
            'John McClane' => 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6e/John_McClane.png/220px-John_McClane.png',
        ];
        $documentoBase = Persona::max('documento');
        $documentoBase = is_numeric($documentoBase) ? (int) $documentoBase + 1 : 10000001;
        $personas = [];

        foreach ($characters as $index => $character) {
            $fullName = trim($character['nombres'] . ' ' . $character['apellidos']);
            $personas[] = [
                'tipo' => $tipos[$index % count($tipos)],
                'genero' => $character['genero'],
                'centro' => $character['centro'],
                'regional' => $character['regional'],
                'tipo_sangre' => $tiposSangre[$index % count($tiposSangre)],
                'documento' => (string) ($documentoBase + $index),
                'nombres' => $character['nombres'],
                'apellidos' => $character['apellidos'],
                'telefono' => '300' . str_pad((string) (1000000 + $index), 7, '0', STR_PAD_LEFT),
                'ficha' => 'F-' . strtoupper(substr($character['nombres'], 0, 2) . substr($character['apellidos'], 0, 2)) . '-' . str_pad($index + 1, 3, '0', STR_PAD_LEFT),
                'foto' => $fotoMap[$fullName] ?? 'https://dummyimage.com/320x320/000/fff&text=' . rawurlencode($fullName),
                'activo' => 1,
                'ficha_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        Persona::insert($personas);
    }
}
